### ISSUE TITLE
rabbitmq fails to start because of ulimit permission issue 

### ISSUE THREAD

**Issue by al3k** [bitnami/bitnami-docker-rabbitmq#86]
**Description**

rabbitmq fails to start because of ulimit permission issue 

**Steps to reproduce the issue:**
Use helm to install latest version : 
helm install --set rabbitmq.username=admin,rabbitmq.password=secretpassword,rabbitmq.erlangCookie=secretcookie stable/rabbitmq

**Describe the results you received:**
microk8s.kubectl logs estranged-clownfish-rabbitmq-0
bash: line 10: ulimit: open files: cannot modify limit: Operation not permitted

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Thu Nov 15 21:12:47 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Sun Nov 11 21:53:22 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 52
 Running: 51
 Paused: 0
 Stopped: 1
Images: 21
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: ecm-devel
ID: TOXD:U4SP:JABO:FPIL:RFHH:ICAW:Y5GD:YVJR:GKRS:OFVE:QXWX:K4Q2
Docker Root Dir: /var/snap/microk8s/common/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 localhost:32000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @al3k, it seems the container executes "ulimit" in "init.sh". It should not be doing that, instead it should verify the values are valid to run it.

We are going to work on fixing this, but unfortunately I cannot give an ETA for when we will start, nor how much time it will take us.

In the meantime, you could fork the container and clean up "rootfs/init.sh" for your chosen container distro.
After that just build the container in your Kubernetes installation's Docker setup, or publish a custom container to Dockerhub and update the Helm chart to point to your new image.

**Comment by Lebed71** [comment]
Hello! I got this problem when update my rabiitmq instance in k8s cluster. This is strange, because previously, everything worked with the same code in init.sh (it was added quite a long time ago)

**Comment by marcosbc** [comment]
Hi @Lebed71, could it be possible your Kubernetes cluster was updated or has some kind of enforced security options enabled?

In any case, we're aware this may cause issues and have opened internal task for fixing this.

Unfortunately we cannot give an ETA for when it will be fixed, so if you need it soon you can build your customized container as I mentioned in my previous comment (and removing the ulimit command).

**Comment by blaketastic2** [comment]
I ran into this same problem on EKS, and it was related to the latest AMI, specifically, this issue - https://github.com/awslabs/amazon-eks-ami/issues/193

**Comment by marcosbc** [comment]
Thanks for sharing! I've also included this information in our internal task, in order to have more context.

**Comment by bfuzze** [comment]
I'm having this problem too.  Building a custom container worked for me, but hope this is fixed soon.

**Comment by marcosbc** [comment]
Thanks for sharing. I've updated our internal task. Are you using EKS as well?

**Comment by JasonChinsen** [comment]
I was running into the same issue when trying to deploy rabbitmq with helm into an EKS cluster. I followed the advice from above and built a custom container removing the ulimt set in init.sh, but it didn't resolve the issue. 

However, I pulled the chart and commented out this line: https://github.com/helm/charts/blob/master/stable/rabbitmq/templates/statefulset.yaml#L88 and run it again and it worked.

```
$kubectl describe pod rabbitmq-0
...
truncated
...
    Command:
      bash
      -ec
      mkdir -p /opt/bitnami/rabbitmq/.rabbitmq/
      mkdir -p /opt/bitnami/rabbitmq/etc/rabbitmq/
      #persist the erlang cookie in both places for server and cli tools
      echo $RABBITMQ_ERL_COOKIE > /opt/bitnami/rabbitmq/var/lib/rabbitmq/.erlang.cookie
      cp /opt/bitnami/rabbitmq/var/lib/rabbitmq/.erlang.cookie /opt/bitnami/rabbitmq/.rabbitmq/
      #change permission so only the user has access to the cookie file
      chmod 600 /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie /opt/bitnami/rabbitmq/var/lib/rabbitmq/.erlang.cookie
      #copy the mounted configuration to both places
      cp  /opt/bitnami/rabbitmq/conf/* /opt/bitnami/rabbitmq/etc/rabbitmq
      # Apply resources limits
      #ulimit -n "${RABBITMQ_ULIMIT_NOFILES}"
      #replace the default password that is generated
      sed -i "s/CHANGEME/$RABBITMQ_PASSWORD/g" /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf
      # Move logs to stdout
      ln -sF /dev/stdout /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@${MY_POD_IP}.log
      ln -sF /dev/stdout /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@${MY_POD_IP}_upgrade.log
      exec rabbitmq-server
...
truncated
...
```

I also tested it with the default image and it works too

```  Normal  Scheduled  2m46s  default-scheduler                                   Successfully assigned default/rabbitmq-0 to ip-10-0-50-227.us-west-2.compute.internal
  Normal  Pulled     2m45s  kubelet, ip-10-0-50-227.us-west-2.compute.internal  Container image "docker.io/bitnami/rabbitmq:3.7.13" already present on machine
  Normal  Created    2m45s  kubelet, ip-10-0-50-227.us-west-2.compute.internal  Created container
  Normal  Started    2m45s  kubelet, ip-10-0-50-227.us-west-2.compute.internal  Started container
```

Hope that this gets updated soon :)

Thanks,

**Comment by hunterchris** [comment]
From the `amazon-eks-node-1.12-v20190329` AMI's changelog (https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md), this seems to be resolved
- 9f20002 Removed ulimit reduction:

**Comment by marcosbc** [comment]
Thanks for sharing @hunterchris!

As for the changes in the container images, we still have not implemented a fix for them not to execute `ulimit` unless needed, but unfortunately I cannot offer an ETA.

In any case it seems the AMI was changed meaning the images should work for most platforms now.

**Comment by ameyspant** [comment]
> fork the container and clean up "rootfs/init.sh"

How to do this?

**Comment by juan131** [comment]
Hi @ameyspant 

> How to do this?

That's an old comment and it doesn't apply to the current structure in the container scripts anymore. As you can see in the section below, there's an environment variable `RABBITMQ_ULIMIT_NOFILES` that can be used to modify the maximum number of open file descriptors:

- https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables

This is the line where that env. variable is used: https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L512

That said, by default the container is executed with a non-root user (see https://github.com/bitnami/bitnami-docker-rabbitmq#why-use-a-non-root-container), and it's highly likely that it won't be able to modify the Kernel unless you forced it to be executed as root.

**Comment by brodul** [comment]
There is a workaround ... simply set:
```
# workaround for https://github.com/bitnami/bitnami-docker-rabbitmq/issues/86
ulimitNofiles: ""
```
in your `values.yaml`.

If the `RABBITMQ_ULIMIT_NOFILES` is an empty string the `ulimit` is not set.
https://github.com/bitnami/bitnami-docker-rabbitmq/blob/3.8.16-debian-10-r12/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L734

:beers:

**Comment by juan131** [comment]
Correct @brodul ! If you set `RABBITMQ_ULIMIT_NOFILES` with  an empty string, this value is ignored.

Indeed, I think we can consider this issue "done". The container logic was moved to bash scripts some time ago, and now the new logic allows user to skip the `ulimit` command. 

Please feel free to reopen the issue if you require further help, but I consider it solved at this moment.
